# Exercise 1 

In this exercise, we will go over an object-oriented programming exercises related to standard operations with `pandas` data frames. 

### Exercise 1(a) (10 points)

Create a class called `DataFrameProcessor` that will handle basic operations on a pandas DataFrame. Your class should:

1. Initialize with a pandas DataFrame.
2. Have a method get_column_stats(column_name) that returns the mean, median, and standard deviation of the specified column.
3. Have a method filter_rows(column_name, threshold) that returns a new DataFrame with rows where the values in the specified column are greater than the given threshold.
4. Have a method add_new_column(column_name, data) that adds a new column with the specified name and data to the DataFrame.

In [6]:
import pandas as pd  


class DataFrameProcessor: 
    def __init__(self, df):
        self.df = df 

    def get_column_stats(self, column_name):
        mean = self.df[column_name].mean()
        median = self.df[column_name].median() 
        std = self.df[column_name].std()

        return mean, median, std 

    def filter_rows(self, column_name, threshold):
        filtered_df = self.df.loc[
            self.df[column_name] > threshold
        ] 

        return filtered_df 

    def add_new_column(self, column_name, data): 
        self.df[column_name] = data 

        return self.df

### Exercise 1(b) (3 points)

Create a data frame called `df` with three columns and 20 rows. Fill the data frame with random integers from 1 to 20. Hint: use `np.random.randint` from `numpy` to generate the random integers.

In [11]:
import numpy as np 

df = pd.DataFrame({
    "col_1": np.random.randint(1, 21, 20), 
    "col_2": np.random.randint(1, 21, 20),
    "col_3": np.random.randint(1, 21, 20)
}) 

df

    col_1  col_2  col_3
0       3     17      2
1       9     18     16
2      13      4     16
3       1      5      4
4      10      7      5
5       6     19      6
6      10     18     16
7      19      5     16
8      10     15      7
9       3     17     17
10     16      9     11
11      7     19     18
12      1      6      1
13     12      3      1
14      1     14      3
15     20     11      6
16     19      2      6
17     17     15      3
18     19     10      2
19      3      8      1

### Exercise 1(c) (4 points)

Using the `DataFrameProcessor` class, report the stats for each of the columns in `df`.

In [12]:
processor = DataFrameProcessor(df) 

for column in df.columns:
    print(column, processor.get_column_stats(column))

col_1 (np.float64(9.95), np.float64(10.0), np.float64(6.7158492820303355))
col_2 (np.float64(11.1), np.float64(10.5), np.float64(5.892903850350325))
col_3 (np.float64(7.85), np.float64(6.0), np.float64(6.293480335779409))

### Exercise 1(d) (3 points)

Filter the rows where `col_3` is greater than 12.

In [13]:
filtered_df = processor.filter_rows("col_3", 12) 

filtered_df

    col_1  col_2  col_3
1       9     18     16
2      13      4     16
6      10     18     16
7      19      5     16
9       3     17     17
11      7     19     18

### Exercise 1(e) (3 points)

Create a list with random intergers from 1 to 20. Add the list to `df` as new column called `col_4`.

In [14]:
new_data = list(np.random.randint(1, 21, 20)) 

processor.add_new_column("col_4", new_data) 

df

    col_1  col_2  col_3  col_4
0       3     17      2     11
1       9     18     16      5
2      13      4     16      6
3       1      5      4     15
4      10      7      5      2
5       6     19      6     14
6      10     18     16      7
7      19      5     16     18
8      10     15      7      1
9       3     17     17      9
10     16      9     11      8
11      7     19     18      9
12      1      6      1      5
13     12      3      1      6
14      1     14      3     14
15     20     11      6     18
16     19      2      6     13
17     17     15      3     11
18     19     10      2     19
19      3      8      1     12

# Exercise 2 (10 points)

Data pre-processing with OOP. Create a Python class called `DataPreprocessor` that:

1. Takes a pandas DataFrame as input.
2. Provides methods to:
   - Handle missing values by filling them with the column mean.
   - Normalize numerical columns between 0 and 1.
3. Returns the cleaned DataFrame when called with `.transform()`

Consider `df` as DataFrame to test the class.

```
data = {
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "gender": ["M", "F", "M", "F", "M"]
}
df = pd.DataFrame(data)
```

In [15]:
import pandas as pd  
import numpy as np  


class DataFrameProcessor: 
    def __init__(self, df): 
        self.df = df  

    def fill_missing_values(self): 
        numeric_columns = self.df.select_dtypes(include="number").columns 

        for column in numeric_columns:
            mean_value = self.df[column].mean() 
            self.df[column] = self.df[column].fillna(mean_value) 

        return self.df 

    def normalize_columns(self): 
        numeric_columns = self.df.select_dtypes(include="number").columns 

        for column in numeric_columns:
            minimum = self.df[column].min()
            maximum = self.df[column].max() 

            self.df[column] = (
                (self.df[column] - minimum) / 
                (maximum - minimum)
            )
        return self.df

    def transform(self):
        self.fill_missing_values() 
        self.normalize_columns() 

        return self.df

# Exercise 3 

In this exercise, we will practice `merge` with `pandas` data frames. Merging in `pandas` is a way of combining two data frames based on a common column or set of columns. Think of it like putting together pieces of a puzzle where both tables have a shared piece of information (like a key or ID number) that helps you connect the rows that belong together.

### Exercise 3(a) (2 points)

Load the `pandas` library.

In [16]:
import pandas as pd

### Exercise 3(b) (4 points)

Create three `pandas` data-frames based on the following raw data:

```
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
```

Call them `dat_1`, `dat_2`, and `dat_3`, respectively.

In [17]:
raw_data_1 = {
    "subject_id": ["1", "2", "3", "4", "5"],
    "first_name": ["Alex", "Amy", "Allen", "Alice", "Ayoung"],
    "last_name": ["Anderson", "Ackerman", "Ali", "Aoni", "Atiches"]
}

raw_data_2 = {
    "subject_id": ["4", "5", "6", "7", "8"],
    "first_name": ["Billy", "Brian", "Bran", "Bryce", "Betty"],
    "last_name": ["Bonder", "Black", "Balwner", "Brice", "Btisan"]
}

raw_data_3 = {
    "subject_id": ["1", "2", "3", "4", "5", "7", "8", "9", "10", "11"],
    "test_id": [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]
} 

dat_1 = pd.DataFrame(raw_data_1)

dat_2 = pd.DataFrame(raw_data_2) 

dat_3 = pd.DataFrame(raw_data_3)

### Exercise 3(c) (3 points)

Combine `dat_1` and `dat_2` along the rows and call the resulting data frame `all_data`.

In [18]:
all_data = pd.concat([dat_1, dat_2]) 

all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

### Exercise 3(d) (3 points)

Combine `dat_1` and `dat_2` along the columns and call the resulting data frame `all_data_col`.

In [19]:
all_data_col = pd.concat([dat_1, dat_2], axis=1) 

all_data_col

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

### Exercise 3(e) (3 points)

Merge `all_data` and `dat_3` using `subject_id` as the key variable, and call the resulting data frame `dat_merge`.

In [20]:
dat_merge = pd.merge(
    all_data,
    dat_3,
    on="subject_id"
) 

dat_merge

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16
5          4      Billy    Bonder       61
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

### Exercise 3(f) (3 points)

Merge `dat_1` and `dat_2` using `subject_id` as the key variable, and call the resulting data frame `dat_merge_1`.

In [21]:
dat_merge_1 = pd.merge(
    dat_1,
    dat_2,
    on="subject_id"
) 

dat_merge_1

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Exercise 3(g) (3 points)

Merge all the values in `dat_1` and `dat_2`, using `subject_id` as the key variable, with matching records from the left data frame. Call the resulting data frame `dat_merge_2`.

In [22]:
dat_merge_2 = pd.merge(
    dat_1,
    dat_2,
    on="subject_id",
    how="left"
)  

dat_merge_2

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black

# Exercise 4

In this exercise, we will practice functional programming with `pandas` data frame. Functional programming concepts with `pandas` involves using `apply()`, `map()`, and `lambda()` functions. 

### Exercise 4(a) (3 points)

Imagine you are working with a data set of customers that includes their purchase amounts in different categories. The goal is to apply transformations and extract insights using functional programming techniques. Create the below `pandas` data frame.

```
import pandas as pd

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Groceries': [120, 150, 80, 90, 130],
    'Electronics': [200, 0, 100, 300, 150],
    'Clothing': [50, 60, 45, 70, 30]
}

df = pd.DataFrame(data)
```

In [23]:
import pandas as pd

data = {
    "Customer_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Groceries": [120, 150, 80, 90, 130],
    "Electronics": [200, 0, 100, 300, 150],
    "Clothing": [50, 60, 45, 70, 30]
}

df = pd.DataFrame(data)

df

   Customer_ID     Name  Groceries  Electronics  Clothing
0          101    Alice        120          200        50
1          102      Bob        150            0        60
2          103  Charlie         80          100        45
3          104    David         90          300        70
4          105      Eva        130          150        30

### Exercise 4(b) (3 points)

Use the `apply()` function to calculate the total spending for each customer (sum of `Groceries`, `Electronics`, and `Clothing`).

In [25]:
df["Total_Spending"] = df.apply(
    lambda row: row["Groceries"] + row["Electronics"] + row["Clothing"],
    axis=1
) 

df

   Customer_ID     Name  Groceries  Electronics  Clothing  Total_Spending
0          101    Alice        120          200        50             370
1          102      Bob        150            0        60             210
2          103  Charlie         80          100        45             225
3          104    David         90          300        70             460
4          105      Eva        130          150        30             310

### Exercise 4(c) (3 points)

Use a `lambda` function to classify customers as `High`, `Medium`, or `Low` spenders based on their total spending:

- High: Total spending >= 400
- Medium: Total spending between 200 and 399
- Low: Total spending < 200

In [26]:
df["Spending_level"] = df["Total_Spending"].apply(
    lambda x: "High" if x >= 400
    else "Medium" if x >= 200 
    else "Low"
) 

df

,Customer_ID,Name,Groceries,Electronics,Clothing,Total_Spending,Spending_level
0,101,Alice,120,200,50,370,Medium
1,102,Bob,150,0,60,210,Medium
2,103,Charlie,80,100,45,225,Medium
3,104,David,90,300,70,460,High
4,105,Eva,130,150,30,310,Medium

### Exercise 4(d) (3 points)

Calculate the percentage of spending in `Electronics` compared to the `Total_Spend` for each customer.

In [34]:
df["Electronics_Percentage"] = df.apply(
    lambda row: (row["Electronics"] / row["Total_Spending"]) * 100,
    axis=1
)

df

,Customer_ID,Name,Groceries,Electronics,Clothing,Total_Spending,Spending_level,Electronics_Percentage
0,101,Alice,120,200,50,370,Medium,54.054054
1,102,Bob,150,0,60,210,Medium,0.000000
2,103,Charlie,80,100,45,225,Medium,44.444444
3,104,David,90,300,70,460,High,65.217391
4,105,Eva,130,150,30,310,Medium,48.387097

### Exercise 4(e) (4 points)

Write a custom function that can be passed to `apply()` to give a 10% discount on electronics spending if a customer's total spend is above $400.

In [35]:
def electronics_discount(row):
    if row["Total_Spending"] > 400:
        return row["Electronics"] * 0.90 
    else:
        return row["Electronics"] 

df["Discounted_Electronics"] = df.apply(
    electronics_discount,
    axis=1 

) 

df

,Customer_ID,Name,Groceries,Electronics,Clothing,Total_Spending,Spending_level,Electronics_Percentage,Discounted_Electronics
0,101,Alice,120,200,50,370,Medium,54.054054,200.0
1,102,Bob,150,0,60,210,Medium,0.000000,0.0
2,103,Charlie,80,100,45,225,Medium,44.444444,100.0
3,104,David,90,300,70,460,High,65.217391,270.0
4,105,Eva,130,150,30,310,Medium,48.387097,150.0